image/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from authy.views import UserProfile,  follow
from comment.views import delete_cmt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
    path('user/', include('authy.urls')),
    path('direct/', include('direct.urls')),
    path('notifications/', include('notifications.urls')),
    path('<username>/', UserProfile, name='profile'),
    path('<username>/saved', UserProfile, name='profilefavorites'),
    path('<username>/follow/<option>', follow, name='follow'),
    path('<cmt_id>/delete', delete_cmt, name='delete-comment'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path
from notifications.views import ShowNOtifications, DeleteNotification


urlpatterns = [
   	path('', ShowNOtifications, name='show-notifications'),
   	path('<noti_id>/delete', DeleteNotification, name='delete-notification'),
	   

]

post/urls.py
from django.conf import settings
from django.urls import path
from post.views import index, NewPost, PostDetails, tags, like, favorite,  search, usersettings, EditPost, delete_post, contact
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
   	path('', index, name='index'),
   	path('newpost/', NewPost, name='newpost'),
   	path('<uuid:post_id>', PostDetails, name='postdetails'),
   	path('<uuid:post_id>/like', like, name='postlike'),
   	path('<uuid:post_id>/favorite', favorite, name='postfavorite'),
   	path('tag/<slug:tag_slug>', tags, name='tags'),
	path('search/', search, name='search'),
	url('settings/', usersettings, name="usersettings"),
	path('editpost/<uuid:post_id>', EditPost, name='edit-post'),
	path('deletepost/<uuid:post_id>', delete_post, name='delete-post'),
	path('contactus/',contact, name='contactus' ),
]

notifications/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Notification(models.Model):
	NOTIFICATION_TYPES = ((1,'Like'),(2,'Comment'), (3,'Follow'))

	post = models.ForeignKey('post.Post', on_delete=models.CASCADE, related_name="noti_post", blank=True, null=True)
	sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_from_user")
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_to_user")
	notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
	text_preview = models.CharField(max_length=90, blank=True)
	date = models.DateTimeField(auto_now_add=True)
	is_seen = models.BooleanField(default=False)

authy/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import fields
from authy.models import Profile

def ForbiddenUsers(value):
	forbidden_users = ['admin', 'css', 'js', 'authenticate', 'login', 'logout', 'administrator', 'root',
	'email', 'user', 'join', 'sql', 'static', 'python', 'delete']
	if value.lower() in forbidden_users:
		raise ValidationError('Invalid name for user, this is a reserverd word.')

def InvalidUser(value):
	if '@' in value or '+' in value or '-' in value:
		raise ValidationError('This is an Invalid user, Do not user these chars: @ , - , + ')

def UniqueEmail(value):
	if User.objects.filter(email__iexact=value).exists():
		raise ValidationError('User with this email already exists.')

def UniqueUser(value):
	if User.objects.filter(username__iexact=value).exists():
		raise ValidationError('User with this username already exists.')

class SignupForm(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(), max_length=30, required=True,)
	email = forms.CharField(widget=forms.EmailInput(), max_length=100, required=True,)
	password = forms.CharField(widget=forms.PasswordInput())
	confirm_password = forms.CharField(widget=forms.PasswordInput(), required=True, label="Confirm your password.")

	class Meta:

		model = User
		fields = ('username', 'email', 'password')

	def __init__(self, *args, **kwargs):
		super(SignupForm, self).__init__(*args, **kwargs)
		self.fields['username'].validators.append(ForbiddenUsers)
		self.fields['username'].validators.append(InvalidUser)
		self.fields['username'].validators.append(UniqueUser)
		self.fields['email'].validators.append(UniqueEmail)

	def clean(self):
		super(SignupForm, self).clean()
		password = self.cleaned_data.get('password')
		confirm_password = self.cleaned_data.get('confirm_password')

		if password != confirm_password:
			self._errors['password'] = self.error_class(['Passwords do not match. Try again'])
		return self.cleaned_data

class ChangePasswordForm(forms.ModelForm):
	id = forms.CharField(widget=forms.HiddenInput())
	old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium'}), label="Old password", required=True)
	new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium'}), label="New password", required=True)
	confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium'}), label="Confirm new password", required=True)

	class Meta:
		model = User
		fields = ('id', 'old_password', 'new_password', 'confirm_password')

	def clean(self):
		super(ChangePasswordForm, self).clean()
		id = self.cleaned_data.get('id')
		old_password = self.cleaned_data.get('old_password')
		new_password = self.cleaned_data.get('new_password')
		confirm_password = self.cleaned_data.get('confirm_password')
		user = User.objects.get(pk=id)
		if not user.check_password(old_password):
			self._errors['old_password'] =self.error_class(['Old password do not match.'])
		if new_password != confirm_password:
			self._errors['new_password'] =self.error_class(['Passwords do not match.'])
		return self.cleaned_data

class EditProfileForm(forms.ModelForm):
	picture = forms.ImageField(required=False)
	background = forms.ImageField(required=False)
	first_name = forms.CharField(widget=forms.TextInput(), max_length=50, required=False)
	last_name = forms.CharField(widget=forms.TextInput(), max_length=50, required=False)
	location = forms.CharField(widget=forms.TextInput(), max_length=25, required=False)
	url = forms.URLField(widget=forms.TextInput(), max_length=60, required=False)
	profile_info = forms.CharField(widget=forms.TextInput(), max_length=260, required=False)

	class Meta:
		model = Profile
		fields = ('picture', 'background','first_name', 'last_name', 'location', 'url', 'profile_info')

post/forms.py
from django import forms
from django.db.models import fields
from post.models import Post, contact

from django.forms import ClearableFileInput

class NewPostForm(forms.ModelForm):
	content = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': False}))
	caption = forms.CharField(widget=forms.Textarea(attrs={'class': 'input is-medium'}), required=True)
	tags = forms.CharField(widget=forms.TextInput(attrs={'class': 'input is-medium'}), required=True)

	class Meta:
		model = Post
		fields = ('content', 'caption', 'tags')

class contactform(forms.ModelForm):
	title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input is-medium'}), required=True)
	message = forms.CharField(widget=forms.Textarea(attrs={'class': 'input is-medium'}), required=True)

	class Meta:
		model = contact
		fields = ('title', 'message')

notifications/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse

from notifications.models import Notification
# Create your views here.
@login_required
def ShowNOtifications(request):
	user = request.user
	notifications = Notification.objects.filter(user=user).order_by('-date')
	Notification.objects.filter(user=user, is_seen=False).update(is_seen=True)

	template = loader.get_template('notifications.html')

	context = {
		'notifications': notifications,
	}

	return HttpResponse(template.render(context, request))

@login_required
def DeleteNotification(request, noti_id):
	user = request.user
	Notification.objects.filter(id=noti_id, user=user).delete()
	return redirect('show-notifications')


def CountNotifications(request):
	count_notifications = 0
	if request.user.is_authenticated:
		count_notifications = Notification.objects.filter(user=request.user, is_seen=False).count()

	return {'count_notifications':count_notifications}
	

image/templates/change_password.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
        
{% block content %}
<style>
body{
  background-color: azure;
}
#id_old_password{
      border-radius: 20px;
    border-color: blue;
    background-color: black;
    color:white;
    margin-top:5px;
}
#id_new_password{
      border-radius: 20px;
    border-color: blue;
    background-color: black;
    color:white;
    margin-top:5px;
}
#id_confirm_password{
      border-radius: 20px;
    border-color: blue;
    background-color: black;
    color:white;
    margin-top:5px;
}

</style>

<div class="card" style="margin-top:30px; max-width:800px;border-color:azure; background-color: azure;align-content:center;">
    <form method="post" action="" role="form" class="col s12">
    </h3>
      <div class="row">
        {% csrf_token %}
        {{ form.id | as_crispy_field }}
        <div class="input-field col s12">
          {{ form.old_password | as_crispy_field }}
        </div>
      </div>
        <div class="row">
        <div class="input-field col s12">
          {{ form.new_password | as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          {{ form.confirm_password | as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
        </div>
      </div>
      <button class="btn btn-outline-primary" style="margin-top:20px; background-color:black; border-radius:20px;" type="submit" name="action">Change Password</button>
    </form>
  </div>

{% endblock %}

image/templates/change_password_done.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	<br>
	<br>
	<br>
	<br>
	<div class="col s12 center-align">
		<i class="large material-icons green-text">check_circle</i>
	</div>
	<div class="col s12 center-align">
		<h4>Your password has been succesfully changed</h4>
	</div>


</div>

<br>
<br>
{% endblock %}

image/templates/competition.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} 
{% block content %}
<style>
  nav {
    background-color: aliceblue !important;
  }
  body {
    background-color: aliceblue !important;
  }
  #id_caption {
    border-color: aliceblue;
    border-bottom-color:blue;
    border-radius:0px;
    height: 100px;
    background-color: aliceblue !important;
  }
   #id_tags {
    border-color: aliceblue;
    border-bottom-color:blue;
    border-radius:0px;
    background-color: aliceblue !important;
  }
</style>
<div class="columns" style="background-color: aliceblue">
  <div
    class=""
    style="
      display: flex;
      justify-content: center;
      width: 100%;
      align-items: center;
    "
  >
    <div
      class="card mt-4 mb-4 ml-auto mr-auto"
      style="border: white; width: 80%; background-color: aliceblue"
    >
      <form method="post" action="" enctype="multipart/form-data" role="form">
        {% csrf_token %}
        <h3 class="title text-center">Submit your Image</h3>
        <hr style="color: black !important; width: 100%" />
        <div class="field" style="width: 90%">
          <p class="control has-icons-left">
            {{ form.content | as_crispy_field }}

            <label class="label is-medium">Choose your files</label>
          </p>
        </div>

        <div class="field">
          <p class="control has-icons-left">
            <label class="label is-medium">
              What you think about your Image ...
            </label>

            
            {{ form.caption | as_crispy_field }}
          </p>
        </div>

        <div class="field">
          <p class="control has-icons-left">
            {{ form.tags | as_crispy_field}}

            <label class="label is-medium"
              >Tags (add tags, separeted by commas with space)</label
            >
          </p>
        </div>

        <div class="field">
          <p class="control">
            <button
              type="submit"
              name="action"
              class="btn btn-outline-success"
              style="width: 100%"
            >
              Submit
            </button>
          </p>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

image/templates/edit_profile.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} {% block content %}

<style>
nav{
  background-color: aquamarine !important;
}
nav .shadow{
  background-color:white !important;
}
body{
  background-color: aquamarine;
}
#id_first_name{
      background-color: black;
    color: white;
    border-radius: 20px;

}
#id_last_name{
    background-color: black;
    color: white;
    border-radius: 20px;

}
#id_url{
    background-color: black;
    color: white;
    border-radius: 20px;

}
#id_location{
    background-color: black;
    color: white;
    border-radius: 20px;

}
#id_profile_info{
    background-color: black;
    color: white;
    border-radius: 20px;

}
#id_picture{
  width:90%;
}
#id_background{
  width:90%;
}
</style>

<div class="container my-4">
  <div class="" style="">
    <div class="card" style="border-radius:20px;">
      
        <form
          method="post"
          enctype="multipart/form-data"
          action=""
          role="form"
          style=""
        >
        <div class="card-header text-center bg-info text-white" style="border-top-right-radius:20px;border-top-left-radius:20px;">
       Edit Profile
        </div>
        <div class="card-body">
          {% csrf_token %}

          <div class="field">
            <div class="file is-boxed">
              {{ form.picture | as_crispy_field }}
            </div>
          </div>
          <div class="field">
            <div class="file is-boxed">
              {{ form.background | as_crispy_field }}
            </div>
          </div>
          <div class="field">
            <div class="control">{{ form.first_name | as_crispy_field }}</div>
          </div>

          <div class="field">
            <div class="control">{{ form.last_name | as_crispy_field }}</div>
          </div>

          <div class="field">
            <div class="control">{{ form.location | as_crispy_field }}</div>
          </div>

          <div class="field">
            <div class="control">{{ form.url | as_crispy_field }}</div>
          </div>

          <div class="field">
            <div class="control">{{ form.profile_info | as_crispy_field }}</div>
          </div>

          <div class="row">
            <div class="col s12">
              <span style="color: red; font-weight: bold"
                >{{ form.errors }}</span
              >
            </div>
          </div>

          <div class="field" style="margin-top: 10px">
            <p class="control">
              <button
                type="submit"
                style=" width: 100%; border-radius:20px; "
                value="login"
                class="btn btn-outline-success"
              >
                Update
              </button>
            </p>
          </div>
          </div>
        </form>
      
    </div>
  </div>
</div>



{% endblock %}

image/templates/editpost.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} {% block content %}

<style>
nav{
  background-color: aquamarine !important;
}
nav .shadow{
  background-color:white !important;
}
body{
  background-color: aquamarine;
}

#id_tags{
    border-color: white;
    border-left-color: aquamarine;

}
#id_caption{
    border-color: white;
    border-left-color: aquamarine;
    height: auto;
}
#id_picture{
  width:90%;
}
#id_content{
  width:90%;
}
  @media screen and (max-width: 800px) {
    #img {
      max-width: 600px !important;
    }
  }
    @media screen and (max-width: 600px) {
    #img {
      max-width: 400px !important;
    }
    @media screen and (max-width: 400px) {
    #img {
      max-width: 300px !important;
    }
    @media screen and (max-width: 300px) {
    #img {
      max-width: 220px !important;
    }
  }
</style>

<div class="container my-4">
  <div class="" style="">
    <div
        class=""
        style="
        width:100%;
        padding-bottom:20px;
          display: inline-flex;
          height: 100% !important;
          flex-wrap: nowrap;
          flex-direction: row;
          align-content: center;
          justify-content: center;
          align-items: center;
        "
      >
             {% for cont in postss.content.all %}
        <!-- Full-width images with number and caption text -->
        <div class="">
          {% if cont.file.name|slice:"-4:" == 'jpeg' or cont.file.name|slice:"-3:" == 'png' or cont.file.name|slice:"-3:" == 'jpg' %}
          <figure class="">
            <img
              id="img" class="shadow"
              style="border-radius: 30px;  margin-bottom:-15px; max-width:800px;"
              src="{{ cont.file.url }}"
              alt="Placeholder image"
            />
          </figure>
          {% else %}
          <a href="{{ cont.get_absolute_url }}">
            <video class="shadow"
              id="img" style="border-radius: 30px"
              controls
              autoplay
              muted
              loop="true"
              preload="metadata"
            >
              <source
                id="img"
                style="border-radius: 30px"
                src="{{ cont.file.url }}#t=0.5"
                type="video/mp4"
              />
            </video>
          </a>
          {% endif %}
        </div>
        {% endfor %}   
        </div>
    <div class="card" style="border-radius:20px;">
      
        <form
          method="post"
          enctype="multipart/form-data"
          action=""
          role="form"
          style=""
        >
        <div class="card-header text-center bg-info text-white" style="border-top-right-radius:20px;border-top-left-radius:20px;">
       Edit Post
        </div>
        <div class="card-body">
          {% csrf_token %}

          <div class="field">
            <div class="file is-boxed">
              {{ form.content | as_crispy_field }}
            </div>
          </div>
          <div class="field">
            <div class="file is-boxed">
              {{ form.caption | as_crispy_field }}
            </div>
          </div>
          <div class="field">
            <div class="control">{{ form.tags | as_crispy_field }}
            <label class="label is-medium">Tags (add tags, separeted by space)</label></div>
          </div>



          <div class="row">
            <div class="col s12">
              <span style="color: red; font-weight: bold"
                >{{ form.errors }}</span
              >
            </div>
          </div>

          <div class="field" style="margin-top: 10px">
            <p class="control">
              <button
                type="submit"
                style=" width: 100%; border-radius:20px; border-color:aquamarine;"
                value="login"
                class="btn btn-outline-info"
              >
                Update
              </button>
            </p>
          </div>
          </div>
        </form>
      
    </div>
  </div>
</div>



{% endblock %}

image/templates/index.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block content %}



<body  style="width:100%; background-color:black !important;">

<style>



/* Responsive layout - makes a two column-layout instead of four columns */
@media screen and (max-width: 800px) {
  #card {
   
    width: 100% !important;
   
  }
    #img{
   
    width: 100% !important;
   
  }
  #video{
   
    width: 100% !important;
   
  }
  #figure{
    margin-right: -4px!important;
  }

}

@media screen and (max-width: 720px) {
  #plus{
    bottom:85px !important;
    right: -10px !important;
  }
}

#plus:hover{
  background-color:aquamarine;
  border-color:white;
}
/* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  #card {
   
    width: 100% !important;
    height:auto !important;
  
  }
  #img{
   
    width: 100% !important;
    height:auto !important;
    margin:-1px -2px -1px !important;
   
  }
  #video{
   
    width: 100% !important;
    height:auto !important;
   
  }

}
</style>


<!-- Header -->

<!-- Photo Grid -->
<div class="row" style=" padding-top:35px;padding-bottom:95px;"> 
  <div class="column" style="display: inline-flex;
  justify-content: space-evenly;
  align-items: center;
  flex-wrap: nowrap;
  flex-direction: column;
  align-content: center;">
  {% for post_item in post_items %}
   {% if post_item.content.first.file.name|slice:"-4:" == 'jpeg' or post_item.content.first.file.name|slice:"-3:" == 'png' or post_item.content.first.file.name|slice:"-3:" == 'jpg' %}
    <div class="card" id="card" style=" margin-bottom:15px !important; border-radius:0px; width:635px;  background-color: aliceblue; border-color:white; border-width:1px;">
    <figure class="" style="" id="figure">
      <a href="{{ post_item.get_absolute_url }}">
        <img id="img" style="border-radius:0px; margin:-2px -1px -2px; width:635px;" class="" src="{{ post_item.content.first.file.url }}" alt="Placeholder image">
      </a>
    </figure>
    <div style="display:flex; 
    justify-content:center;">
    <div style="width:80%;" class="text-center">
    <b>{{ post_item.caption|slice:":200" }} . . . .</b>
    </div>
  </div>

        <figure class="" style="padding-left:20px;">
          {% if post_item.user.profile.picture %}
            <a style="color:black; text-decoration:none;" href="{% url 'profile' post_item.user %}"><img style="width:25px; height:25px; border-radius:20px; margin-top:-5px;" src="{{ post_item.user.profile.picture.url }}" alt="Placeholder image"> &nbsp {{ post_item.user.profile.first_name }} {{ post_item.user.profile.last_name }}</a>
          {% else %}
          <a style="color:black; text-decoration:none;" href="{% url 'profile' post_item.user %}">
            <img  style="width:25px; height:25px; border-radius:20px; margin-top:-5px;" src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
             &nbsp {{ post_item.user.profile.first_name }} {{ post_item.user.profile.last_name }}</a>

          {% endif %}
        </figure>

     

    <div class="boxx" style="display: inline-flex;
    flex-wrap: nowrap;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;">
    <div>
      <a style="padding-left:20px;" href="{% url 'postlike' post_item.id %}"><img style="height:34px;" class="" src="../static/img/heart.png"></a>
      <p style="margin-left:55px;  margin-top:-30px; color:black;" >{{ post_item.likes }}&nbspLikes</p>  
       </div>
       <div  style=" margin-top:-5px; margin-right:20px;">
       <a style="" href="{% url 'postfavorite' post_item.id %}"><img style="height:28px;" class="" src="../static/img/save-file.png"></a>
      </div>

    </div>
</div>

  {% else %}
  <div class="card" id="card" style=" margin-bottom:15px !important;  border-radius:20px;  background-color: aliceblue; border-color:blue; border-width:1px;  border-color:blue;  ">
   <div style=" margin-left: -2px;
    margin-right: -2px;">
   <a href="{{ post_item.get_absolute_url }}">
      <video id="video"  width=""  controls autoplay muted loop="true" preload="metadata" style="border-radius:20px;margin-top:-5px !important;  height:260px; ">
        <source  style="border-radius:20px;" src="{{ post_item.content.first.file.url }}#t=0.5" type="video/mp4">        
      </video>      
    </a>
    </div>
        <figure class="" style="padding-left:20px; padding-top:1rem;">
          {% if post_item.user.profile.picture %}
            <a style="color:black; text-decoration:none;" href="{% url 'profile' post_item.user %}"><img style="width:25px; height:25px; border-radius:20px; margin-top:-5px;" src="{{ post_item.user.profile.picture.url }}" alt="Placeholder image"> &nbsp {{ post_item.user.profile.first_name }} {{ post_item.user.profile.last_name }}</a>
          {% else %}
            <img  style="width:25px; height:25px;" src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
            <a href="{% url 'profile' post_item.user %}"><p class="title is-4">{{ post_item.user.profile.first_name }} {{ post_item.user.profile.last_name }}</p></a>

          {% endif %}
        </figure>
    <div class="boxx" style="display: inline-flex;
    flex-wrap: nowrap;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;">
    <div>
      <a style="padding-left:20px;" href="{% url 'postlike' post_item.id %}"><img style="height:34px;" class="" src="../static/img/heart.png"></a>
      <p style="margin-left:55px;  margin-top:-30px; color:black;" >{{ post_item.likes }}&nbspLikes</p>  
       </div>
       <div  style=" margin-top:-5px; margin-right:20px;">
       <a style="" href="{% url 'postfavorite' post_item.id %}"><img style="height:28px;" class="" src="../static/img/save-file.png"></a>
      </div>
   
    </div>
    </div>
    
  {% endif %}

  
  {%endfor %}
  
</div>
</body>
{% endblock %}

image/templates/login.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} 
{% block content %}
<style>
  body {
    background-color: black !important;
    color:white;
  }
</style>
<body style=" background-color:black !important; color:white;">
<section class="section"  style="margin-top: 30px; background-color:black; color:white;">
  <div class="container">
    <div class="columns is-mobile has-text-centered">
      <div class="column is-half is-offset-one-quarter">
        <div class="">
          <div class="card-content">
            <form method="post" action="" role="form">
              {% csrf_token %}
              <h3 class="text-center">Login</h3>

              <div class="field">
                <p class="control has-icons-left"
                  {{ form | crispy }}
                </p>
              </div>


              {% if form.errors %}
              <div class="row">
                <div class="col s12">
                  <span style="color: red; font-weight: bold"
                    >Your username or password did not match.</span
                  >
                </div>
              </div>
              {% endif %}

              <div class="field">
                <p class="control">
                  <button type="submit" value="login" class="btn btn-outline-success" style="">
                    Login
                  </button>
                </p>
              </div>

              <input type="hidden" name="next" value="{{ next }}" />
              <p> If you don't registerd, then </p>
              <a href="{% url 'signup' %}" class="btn btn-outline-info"
                >Create an account</a
              >
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</body>
{% endblock %}

image/templates/newstory.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="columns is-mobile has-text-centered">
  <div class="column is-half is-offset-one-quarter">

    <div class="card">
    <div class="card-content">

    <form method="post" action="" enctype="multipart/form-data" role="form">
    {% csrf_token %}
    <h3 class="title is-1">New Story</h3>

            <div class="field">
              <p class="control has-icons-left">
              <label class="label is-medium">Choose your media</label>
                {{ form.content }}
                <span class="icon is-small is-left">
            <i class="fas fa-lock"></i>
          </span>
        </p>
          </div>

            <div class="field">
              <p class="control has-icons-left">
              <label class="label is-medium">Caption</label>
                {{ form.caption }}
                <span class="icon is-small is-left">
            <i class="fas fa-lock"></i>
          </span>
        </p>
          </div>


      <div class="field">
      <p class="control">
        <button type="submit" name="action" class="button is-success">
          Create
        </button>
      </p>
    </div>


      </div>
</div>







{% endblock %}

image/templates/settings.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
body{
    background-color:black;
}

</style>

<div style="margin-top:30px;">
<a class='card shadow' style="text-decoration:blink; text-align:center;padding:20px;background-color: white;" href="{% url 'profile' user %}">Profile</a>
<hr>
<a class='card shadow' style="text-decoration:blink; text-align:center;padding:20px;background-color: white;" href="{% url 'change_password' %}">Password Change</a>
<hr>
<a class='card shadow' style="text-decoration:blink;text-align:center;padding:20px;background-color: white;" href="{% url 'contactus' %}">Contact</a>
<hr>
<a class='card shadow' style="text-decoration:blink;text-align:center;padding:20px;background-color: white; color:red;" href="{% url 'logout' %}"><b>Log out</b></a>


</div>


{% endblock %}

image/templates/signup.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} 
{% block content %}
<style>
#id_username{
  border-color: white;
    border-bottom-color: blue;
    margin-bottom:10px;
    border-radius:0px !important;
    
}
#id_email{
  border-color: white;
    border-bottom-color: blue;
      margin-bottom:10px;
      border-radius:0px !important;
}
#id_password{
  border-color: white;
    border-bottom-color: blue;
      margin-bottom:10px;
      border-radius:0px !important;
}
#id_confirm_password{
  border-color: white;
    border-bottom-color: blue;
      margin-bottom:10px;
      border-radius:0px !important;
}
</style>


  <section class="section" style="margin-top:30px; color:white;">
    <div class="container">

<div class="columns is-mobile has-text-centered">
  <div class="column is-half is-offset-one-quarter">

    <div class="">
    <div class="card-content">

    <form method="post" action="" role="form">
    {% csrf_token %}
    <h3 class="text-center">Create an account</h3>

            <div class="field">
              <p class="control has-icons-left">
                {{ form | crispy }}
        </p>
          </div>


      <div class="row">
        <div class="col s12">
          <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
        </div>
      </div>

      <div class="field">
      <p class="control">
        <button type="submit" name="action" class="btn btn-outline-success" style="width:200px;">
          Sign Up
        </button>
      </p>
      <p> If you have an account, then </p>
         <a href="{% url 'login' %}" class="btn btn-outline-info"style="width:200px;"
                >Login</a
              >
    </div>


      </div>
</div>


    </div>
  </section>

    </form>
  </div>

{% endblock %}